title: Ed Snider
tagline: Blog
description: 
url: http://edsnider.net
baseurl: /

twitter_username: edsnider
github_username: edsnider

google_analytics: UA—12537982-1

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock