title: Ed Snider
tagline: Blog
email: 
description: > # ignore newlines until "baseurl:"
  
baseurl: "/"
url: "http://edsnider.net"
twitter_username: edsnider
github_username: edsnider

google_analytics: UA—12537982-1

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock