title: Ed Snider
tagline: Blog
email: 
description: > # ignore newlines until "baseurl:"
  
baseurl: "/"
url: "http://edsnider.net"
twitter_username: edsnider
github_username: edsnider

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock